version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
    environment:
      - BROWSERSTACK_USERNAME: orlandoavila_ve9kqN
      - BROWSERSTACK_ACCESS_KEY: LPbotyHHmZWvyWnkxnPH
    steps:
      - checkout
      - run:
          name: Run Appium tests
          command: |
            chmod +x gradlew
            ./gradlew clean test --tests LoginRunner

workflows:
  version: 2
  build-deploy:
    jobs:
      - build